replicaCount: 1

image:
  # We will update this repository URL in Phase 3 once our ECR is fully ready
  repository: 834715822389.dkr.ecr.us-east-1.amazonaws.com/project1-app-repo
  pullPolicy: IfNotPresent
  tag: "c5aaa5d164824d93d165ba69f8eb7e5c7e95e594"

service:
  type: ClusterIP
  port: 5000
