replicaCount: 1

image:
  # We will update this repository URL in Phase 3 once our ECR is fully ready
  repository: 834715822389.dkr.ecr.us-east-1.amazonaws.com/hello-world-app
  pullPolicy: IfNotPresent
  tag: "09d0298a27297280368cc69817e09242543a0987"

service:
  type: ClusterIP
  port: 5000
