replicaCount: 1

image:
  # We will update this repository URL in Phase 3 once our ECR is fully ready
  repository: 834715822389.dkr.ecr.us-east-1.amazonaws.com/project1-app-repo
  pullPolicy: IfNotPresent
  tag: "90c4dd7a85777906a2539b73ba01964f1654538b"

service:
  type: ClusterIP
  port: 5000
