name: "Terraform Infrastructure Destruction"

on:
  workflow_dispatch: # This adds a manual "Run workflow" button in GitHub

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve